In [1]:
import pandas as pd
import pydataset

In [2]:
titanic = pydataset.data('titanic')

In [3]:
titanic.columns

Index(['class', 'age', 'sex', 'survived'], dtype='object')

In [4]:
titanic['class'].describe()

count          1316
unique            3
top       3rd class
freq            706
Name: class, dtype: object

In [5]:
titanic['class'].nbytes

10528

In [7]:
%%time
titanic[titanic['class'] == '3rd class']

Wall time: 3 ms

          class     age    sex survived
611   3rd class  adults    man      yes
612   3rd class  adults    man      yes
613   3rd class  adults    man      yes
614   3rd class  adults    man      yes
615   3rd class  adults    man      yes
616   3rd class  adults    man      yes
617   3rd class  adults    man      yes
618   3rd class  adults    man      yes
619   3rd class  adults    man      yes
620   3rd class  adults    man      yes
621   3rd class  adults    man      yes
622   3rd class  adults    man      yes
623   3rd class  adults    man      yes
624   3rd class  adults    man      yes
625   3rd class  adults    man      yes
626   3rd class  adults    man      yes
627   3rd class  adults    man      yes
628   3rd class  adults    man      yes
629   3rd class  adults    man      yes
630   3rd class  adults    man      yes
631   3rd class  adults    man      yes
632   3rd class  adults    man      yes
633   3rd class  adults    man      yes
634   3rd class  adults    man      yes
635   3rd class  adults    man      yes
636   3rd class  adults    man      yes
637   3rd class  adults    man      yes
638   3rd class  adults    man      yes
639   3rd class  adults    man      yes
640   3rd class  adults    man      yes
641   3rd class  adults    man      yes
642   3rd class  adults    man      yes
643   3rd class  adults    man      yes
644   3rd class  adults    man      yes
645   3rd class  adults    man      yes
646   3rd class  adults    man      yes
647   3rd class  adults    man      yes
648   3rd class  adults    man      yes
649   3rd class  adults    man      yes
650   3rd class  adults    man      yes
651   3rd class  adults    man      yes
652   3rd class  adults    man      yes
653   3rd class  adults    man      yes
654   3rd class  adults    man      yes
655   3rd class  adults    man      yes
656   3rd class  adults    man      yes
657   3rd class  adults    man      yes
658   3rd class  adults    man      yes
659   3rd class  adults    man      yes
660   3rd class  adults    man      yes
661   3rd class  adults    man      yes
662   3rd class  adults    man      yes
663   3rd class  adults    man      yes
664   3rd class  adults    man      yes
665   3rd class  adults    man      yes
666   3rd class  adults    man      yes
667   3rd class  adults    man      yes
668   3rd class  adults    man      yes
669   3rd class  adults    man      yes
670   3rd class  adults    man      yes
671   3rd class  adults    man      yes
672   3rd class  adults    man      yes
673   3rd class  adults    man      yes
674   3rd class  adults    man      yes
675   3rd class  adults    man      yes
676   3rd class  adults    man      yes
677   3rd class  adults    man      yes
678   3rd class  adults    man      yes
679   3rd class  adults    man      yes
680   3rd class  adults    man      yes
681   3rd class  adults    man      yes
682   3rd class  adults    man      yes
683   3rd class  adults    man      yes
684   3rd class  adults    man      yes
685   3rd class  adults    man      yes
686   3rd class  adults    man       no
687   3rd class  adults    man       no
688   3rd class  adults    man       no
689   3rd class  adults    man       no
690   3rd class  adults    man       no
691   3rd class  adults    man       no
692   3rd class  adults    man       no
693   3rd class  adults    man       no
694   3rd class  adults    man       no
695   3rd class  adults    man       no
...         ...     ...    ...      ...
1232  3rd class  adults  women       no
1233  3rd class  adults  women       no
1234  3rd class  adults  women       no
1235  3rd class  adults  women       no
1236  3rd class  adults  women       no
1237  3rd class  adults  women       no
1238  3rd class   child    man      yes
1239  3rd class   child    man      yes
1240  3rd class   child    man      yes
1241  3rd class   child    man      yes
1242  3rd class   child    man      yes
1243  3rd class   child    man      yes
1244  3rd class   child    man      yes
1245  3rd class   child    man      yes
1246  3rd class   child    man      yes
1247  3rd class   child    man      yes
1248  3rd class   child    man      yes
1249  3rd class   child    man      yes
1250  3rd class   child    man      yes
1251  3rd class   child    man       no
1252  3rd class   child    man       no
1253  3rd class   child    man       no
1254  3rd class   child    man       no
1255  3rd class   child    man       no
1256  3rd class   child    man       no
1257  3rd class   child    man       no
1258  3rd class   child    man       no
1259  3rd class   child    man       no
1260  3rd class   child    man       no
1261  3rd class   child    man       no
1262  3rd class   child    man       no
1263  3rd class   child    man       no
1264  3rd class   child    man       no
1265  3rd class   child    man       no
1266  3rd class   child    man       no
1267  3rd class   child    man       no
1268  3rd class   child    man       no
1269  3rd class   child    man       no
1270  3rd class   child    man       no
1271  3rd class   child    man       no
1272  3rd class   child    man       no
1273  3rd class   child    man       no
1274  3rd class   child    man       no
1275  3rd class   child    man       no
1276  3rd class   child    man       no
1277  3rd class   child    man       no
1278  3rd class   child    man       no
1279  3rd class   child    man       no
1280  3rd class   child    man       no
1281  3rd class   child    man       no
1282  3rd class   child    man       no
1283  3rd class   child    man       no
1284  3rd class   child    man       no
1285  3rd class   child    man       no
1286  3rd class   child  women      yes
1287  3rd class   child  women      yes
1288  3rd class   child  women      yes
1289  3rd class   child  women      yes
1290  3rd class   child  women      yes
1291  3rd class   child  women      yes
1292  3rd class   child  women      yes
1293  3rd class   child  women      yes
1294  3rd class   child  women      yes
1295  3rd class   child  women      yes
1296  3rd class   child  women      yes
1297  3rd class   child  women      yes
1298  3rd class   child  women      yes
1299  3rd class   child  women      yes
1300  3rd class   child  women       no
1301  3rd class   child  women       no
1302  3rd class   child  women       no
1303  3rd class   child  women       no
1304  3rd class   child  women       no
1305  3rd class   child  women       no
1306  3rd class   child  women       no
1307  3rd class   child  women       no
1308  3rd class   child  women       no
1309  3rd class   child  women       no
1310  3rd class   child  women       no
1311  3rd class   child  women       no
1312  3rd class   child  women       no
1313  3rd class   child  women       no
1314  3rd class   child  women       no
1315  3rd class   child  women       no
1316  3rd class   child  women       no

[706 rows x 4 columns]

In [8]:
titanic['class'] = titanic['class'].astype('category')

In [9]:
titanic['class'].nbytes

1340

In [10]:
titanic.head()

       class     age  sex survived
1  1st class  adults  man      yes
2  1st class  adults  man      yes
3  1st class  adults  man      yes
4  1st class  adults  man      yes
5  1st class  adults  man      yes